<?php

namespace ForumBundle\Repository;
use ForumBundle\Entity\Question;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{

    public function  derR($q){

        $query= $this->getEntityManager()
            ->createQuery("SELECT m FROM ForumBundle:Question m WHERE m.categorie=:ques ORDER BY m.date DESC")

            ->setParameter('ques',$q);
        $re = new Question();
        $re=$query->getResult();
        if(isset($re[0])) {
            return $re[0] ;
        }else
        {
            return false ;
        }


    }
    public function getNb($v) {

        return $this->createQueryBuilder('r')

            ->select('COUNT(r)')
            ->where('r.categorie =:q')
            ->setParameter('q',$v)

            ->getQuery()

            ->getSingleScalarResult();

    }


}
